spring:
  jpa:
    hibernate:
      dll-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadolivro
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jackson:
    default-property-inclusion: non_null
jwt:
  secret: 254bbdf6-9044-400c-98a2-a88262b57636
  expiration: 999999
